sudo: required
language: generic
services:
  - docker

# Try to always use a tag when you are automating things with Travis or other softwares

before_install:
  - docker build -t nabetse28/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true nabetse28/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-105142294470"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
